const images = {
    recordEdge: require('../Images/recordEdge.png'),
    flip: require('../Images/flip.png'),
    profileIcon: require('../Images/profileIcon.png'),
    recordIconBlue: require('../Images/blueIcons/record.png'),
    recordIconSlate: require('../Images/slateIcons/rechord.png'),
    musicIconSlate: require('../Images/slateIcons/music.png'),
    heartIconSlate: require('../Images/slateIcons/heart.png'),
    heartEmptySlate: require('../Images/slateIcons/heartEmpty.png'),
    locationIconSlate: require('../Images/slateIcons/location.png'),
    cover1: require('../Images/covers/cover1.png'),
    cover2: require('../Images/covers/cover2.png'),
    cover3: require('../Images/covers/cover3.png'),
    cover4: require('../Images/covers/cover4.png'),
    cover5: require('../Images/covers/cover5.png'),
    cover6: require('../Images/covers/cover6.png'),
    cover7: require('../Images/covers/cover7.png'),
    cover8: require('../Images/covers/cover8.png'),
    cover9: require('../Images/covers/cover9.png'),
    logo: require('../Images/Logo.png'),
    navAddPurple: require('../Images/navIcons/addPurple.png'),
    navGlobePurple: require('../Images/navIcons/globePurple.png'),
    navRechordPurple: require('../Images/navIcons/rechordPurple.png'),
    navAddWhite: require('../Images/navIcons/addWhite.png'),
    navGlobeWhite: require('../Images/navIcons/globeWhite.png'),
    navRechordWhite: require('../Images/navIcons/rechordWhite.png'),
}

export default images